-- ==========================================================
-- Aviv Library - Supabase Database & Storage Setup Script
-- Platform Owner: abhikr6714@gmail.com
-- ==========================================================

-- 1. Create the book_submissions table
create table if not exists public.book_submissions (
    id bigint generated by default as identity primary key,
    title text not null,
    author text default 'Unknown Author',
    description text default '',
    category text default 'General',
    year int default 0,
    language text default 'English',
    pages int default 0,
    file_size bigint not null default 0,
    file_path text not null,
    public_url text not null,
    status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
    rejection_reason text default null,
    submitted_by uuid references auth.users(id) on delete set null,
    submitter_name text default 'Anonymous',
    submitter_email text default '',
    created_at timestamptz default now() not null,
    reviewed_at timestamptz default null,
    reviewed_by uuid references auth.users(id) on delete set null
);

-- 2. Create indices for fast querying and filtering
create index if not exists idx_book_submissions_status on public.book_submissions(status);
create index if not exists idx_book_submissions_created_at on public.book_submissions(created_at desc);
create index if not exists idx_book_submissions_submitted_by on public.book_submissions(submitted_by);
create index if not exists idx_book_submissions_submitter_email on public.book_submissions(submitter_email);

-- 3. Enable Row Level Security (RLS)
alter table public.book_submissions enable row level security;

-- Drop existing policies to prevent conflicts
drop policy if exists "Anyone can read accepted books" on public.book_submissions;
drop policy if exists "Submitters can view their own submissions" on public.book_submissions;
drop policy if exists "Owner can view all submissions" on public.book_submissions;
drop policy if exists "Anyone can submit a book for review" on public.book_submissions;
drop policy if exists "Owner can update submissions" on public.book_submissions;
drop policy if exists "Owner can delete submissions" on public.book_submissions;
drop policy if exists "Public read submissions" on public.book_submissions;
drop policy if exists "Anyone can read submissions" on public.book_submissions;

-- Policy 1: Anyone (public, guest, or authenticated) can read submissions
-- This ensures guests can track their submissions on /my-submissions,
-- allows the public catalogue to display accepted books,
-- and prevents RLS errors when inserting new rows with return values.
create policy "Anyone can read submissions"
on public.book_submissions for select
using (true);

-- Policy 2: Anyone (authenticated or guest) can submit a book for review,
-- but the status MUST be 'pending'. Nobody can self-publish without review.
create policy "Anyone can submit a book for review"
on public.book_submissions for insert
with check (status = 'pending');

-- Policy 3: Platform Owner (abhikr6714@gmail.com) can update submissions
-- (e.g. Accept and Publish, or Reject with reason)
create policy "Owner can update submissions"
on public.book_submissions for update
using (
    lower(auth.jwt()->>'email') = 'abhikr6714@gmail.com'
)
with check (
    lower(auth.jwt()->>'email') = 'abhikr6714@gmail.com'
);

-- Policy 4: Platform Owner can delete submissions
create policy "Owner can delete submissions"
on public.book_submissions for delete
using (
    lower(auth.jwt()->>'email') = 'abhikr6714@gmail.com'
);

-- ==========================================================
-- 4. Supabase Storage Setup (Bucket: book-submissions)
-- ==========================================================

-- Insert the storage bucket if not already created
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'book-submissions',
    'book-submissions',
    true,
    52428800, -- 50 MB
    array['application/pdf']
)
on conflict (id) do update set
    public = true,
    file_size_limit = 52428800,
    allowed_mime_types = array['application/pdf'];

-- Storage Policies
drop policy if exists "Public read book-submissions" on storage.objects;
drop policy if exists "Public insert book-submissions" on storage.objects;
drop policy if exists "Owner update book-submissions" on storage.objects;
drop policy if exists "Owner delete book-submissions" on storage.objects;

-- Allow public read access to uploaded books
create policy "Public read book-submissions"
on storage.objects for select
using (bucket_id = 'book-submissions');

-- Allow anyone (guest or signed-in) to upload PDFs directly to book-submissions
create policy "Public insert book-submissions"
on storage.objects for insert
with check (bucket_id = 'book-submissions');

-- Allow platform owner to manage storage objects
create policy "Owner update book-submissions"
on storage.objects for update
using (bucket_id = 'book-submissions' and lower(auth.jwt()->>'email') = 'abhikr6714@gmail.com');

create policy "Owner delete book-submissions"
on storage.objects for delete
using (bucket_id = 'book-submissions' and lower(auth.jwt()->>'email') = 'abhikr6714@gmail.com');
