-- ==========================================================
-- Aviv Library - Supabase Database & Storage Setup Script
-- Role-Based Access Control (RBAC): User vs Owner
-- ==========================================================

-- 1. Create the user_roles table (Role-Based Access Control)
create table if not exists public.user_roles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'user' check (role in ('user', 'owner', 'admin')),
    created_at timestamptz default now() not null
);

-- Enable RLS on user_roles
alter table public.user_roles enable row level security;

-- Allow reading user roles (anyone can read so client & policies can resolve role)
drop policy if exists "Allow read user_roles" on public.user_roles;
drop policy if exists "Admins can view admins" on public.app_admins;
drop policy if exists "Anyone can read app_admins" on public.app_admins;
create policy "Allow read user_roles"
on public.user_roles for select
using (true);

-- Trigger: newly created users automatically get the default 'user' role
create or replace function public.handle_new_user_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_roles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_role on auth.users;
create trigger on_auth_user_created_role
  after insert on auth.users
  for each row execute procedure public.handle_new_user_role();

-- Backfill any existing users in auth.users into user_roles
insert into public.user_roles (user_id, role)
select id, 'user' from auth.users
on conflict (user_id) do nothing;

-- Helper security definer function: checks if authenticated user has 'owner' or 'admin' role
create or replace function public.is_platform_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid()
      and role in ('owner', 'admin')
  );
$$;

-- 2. Create the book_submissions table
create table if not exists public.book_submissions (
    id bigint generated by default as identity primary key,
    title text not null,
    author text default 'Unknown Author',
    description text default '',
    category text default 'General',
    year int default 0,
    language text default 'English',
    pages int default 0,
    file_size bigint not null default 0,
    file_path text not null,
    public_url text not null,
    status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
    rejection_reason text default null,
    submitted_by uuid references auth.users(id) on delete set null,
    submitter_name text default 'Anonymous',
    submitter_email text default '',
    created_at timestamptz default now() not null,
    reviewed_at timestamptz default null,
    reviewed_by uuid references auth.users(id) on delete set null
);

-- 3. Create indices for fast querying and filtering
create index if not exists idx_book_submissions_status on public.book_submissions(status);
create index if not exists idx_book_submissions_created_at on public.book_submissions(created_at desc);
create index if not exists idx_book_submissions_submitted_by on public.book_submissions(submitted_by);
create index if not exists idx_book_submissions_submitter_email on public.book_submissions(submitter_email);

-- 4. Enable Row Level Security (RLS)
alter table public.book_submissions enable row level security;

-- Drop existing policies to prevent conflicts
drop policy if exists "Anyone can read accepted books" on public.book_submissions;
drop policy if exists "Submitters can view their own submissions" on public.book_submissions;
drop policy if exists "Owner can view all submissions" on public.book_submissions;
drop policy if exists "Anyone can submit a book for review" on public.book_submissions;
drop policy if exists "Owner can update submissions" on public.book_submissions;
drop policy if exists "Owner can delete submissions" on public.book_submissions;
drop policy if exists "Public read submissions" on public.book_submissions;
drop policy if exists "Anyone can read submissions" on public.book_submissions;

-- Policy 1: Anyone (public, guest, or authenticated) can read submissions
-- This ensures guests can track their submissions on /my-submissions,
-- allows the public catalogue to display accepted books,
-- and prevents RLS errors when inserting new rows with return values.
create policy "Anyone can read submissions"
on public.book_submissions for select
using (true);

-- Policy 2: Anyone (authenticated or guest) can submit a book for review,
-- but the status MUST be 'pending'. Nobody can self-publish without review.
create policy "Anyone can submit a book for review"
on public.book_submissions for insert
with check (status = 'pending');

-- Policy 3: Platform Admins can update submissions (e.g. Accept and Publish, or Reject with reason)
create policy "Owner can update submissions"
on public.book_submissions for update
using (public.is_platform_admin())
with check (public.is_platform_admin());

-- Policy 4: Platform Admins can delete submissions
create policy "Owner can delete submissions"
on public.book_submissions for delete
using (public.is_platform_admin());

-- ==========================================================
-- 5. Supabase Storage Setup (Bucket: book-submissions)
-- ==========================================================

-- Insert the storage bucket if not already created
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'book-submissions',
    'book-submissions',
    true,
    52428800, -- 50 MB
    array['application/pdf']
)
on conflict (id) do update set
    public = true,
    file_size_limit = 52428800,
    allowed_mime_types = array['application/pdf'];

-- Storage Policies
drop policy if exists "Public read book-submissions" on storage.objects;
drop policy if exists "Public insert book-submissions" on storage.objects;
drop policy if exists "Owner update book-submissions" on storage.objects;
drop policy if exists "Owner delete book-submissions" on storage.objects;

-- Allow public read access to uploaded books
create policy "Public read book-submissions"
on storage.objects for select
using (bucket_id = 'book-submissions');

-- Allow anyone (guest or signed-in) to upload PDFs directly to book-submissions
create policy "Public insert book-submissions"
on storage.objects for insert
with check (bucket_id = 'book-submissions');

-- Allow platform admins to manage storage objects
create policy "Owner update book-submissions"
on storage.objects for update
using (
    bucket_id = 'book-submissions' and
    public.is_platform_admin()
);

create policy "Owner delete book-submissions"
on storage.objects for delete
using (
    bucket_id = 'book-submissions' and
    public.is_platform_admin()
);
