-- ==========================================================
-- Aviv Library - Supabase Schema & Storage Configuration
-- International Standard Architecture (RBAC & Storage Lifecycle)
-- ==========================================================

-- 1. User Roles & Identity System
create table if not exists public.user_roles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'user' check (role in ('user', 'owner', 'admin')),
    uid text unique,
    created_at timestamptz default now() not null
);

-- Ensure uid column exists if table was created previously
alter table public.user_roles add column if not exists uid text unique;

-- Enable Row Level Security
alter table public.user_roles enable row level security;

-- Policy: Allow reading user roles and UIDs
drop policy if exists "Allow read user_roles" on public.user_roles;
create policy "Allow read user_roles"
on public.user_roles for select
using (true);

-- Function: Generates an 8-digit random numeric identifier (10000000 to 99999999)
create or replace function public.generate_unique_8digit_uid()
returns text
language plpgsql
as $$
declare
  candidate_uid text;
  is_unique boolean := false;
begin
  while not is_unique loop
    candidate_uid := floor(10000000 + random() * 90000000)::text;
    select not exists (select 1 from public.user_roles where uid = candidate_uid) into is_unique;
  end loop;
  return candidate_uid;
end;
$$;

-- Trigger: Automatically assign default 'user' role and an 8-digit random UID on user registration
create or replace function public.handle_new_user_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  assigned_uid text;
begin
  assigned_uid := public.generate_unique_8digit_uid();
  insert into public.user_roles (user_id, role, uid)
  values (new.id, 'user', assigned_uid)
  on conflict (user_id) do update set
    uid = coalesce(public.user_roles.uid, assigned_uid);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_role on auth.users;
create trigger on_auth_user_created_role
  after insert on auth.users
  for each row execute procedure public.handle_new_user_role();

-- Backfill any existing users in auth.users into user_roles
insert into public.user_roles (user_id, role, uid)
select id, 'user', public.generate_unique_8digit_uid()
from auth.users
on conflict (user_id) do update set
  uid = coalesce(public.user_roles.uid, public.generate_unique_8digit_uid());

-- Security Definer: Authorizes platform administration operations
create or replace function public.is_platform_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid()
      and role in ('owner', 'admin')
  );
$$;

-- 2. Book Submissions Catalog
create table if not exists public.book_submissions (
    id bigint generated by default as identity primary key,
    title text not null,
    author text default 'Unknown Author',
    description text default '',
    category text default 'General',
    year int default 0,
    language text default 'English',
    pages int default 0,
    file_size bigint not null default 0,
    file_path text not null,
    public_url text not null,
    status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
    rejection_reason text default null,
    submitted_by uuid references auth.users(id) on delete set null,
    submitter_name text default 'Anonymous',
    submitter_email text default '',
    created_at timestamptz default now() not null,
    reviewed_at timestamptz default null,
    reviewed_by uuid references auth.users(id) on delete set null
);

-- Indexing for high performance queries
create index if not exists idx_book_submissions_status on public.book_submissions(status);
create index if not exists idx_book_submissions_created_at on public.book_submissions(created_at desc);
create index if not exists idx_book_submissions_submitted_by on public.book_submissions(submitted_by);
create index if not exists idx_book_submissions_submitter_email on public.book_submissions(submitter_email);

-- Enable Row Level Security on book submissions
alter table public.book_submissions enable row level security;

-- Policies for Book Submissions
drop policy if exists "Anyone can read submissions" on public.book_submissions;
create policy "Anyone can read submissions"
on public.book_submissions for select
using (true);

drop policy if exists "Anyone can submit a book for review" on public.book_submissions;
create policy "Anyone can submit a book for review"
on public.book_submissions for insert
with check (status = 'pending');

drop policy if exists "Owner can update submissions" on public.book_submissions;
create policy "Owner can update submissions"
on public.book_submissions for update
using (public.is_platform_admin())
with check (public.is_platform_admin());

drop policy if exists "Owner can delete submissions" on public.book_submissions;
create policy "Owner can delete submissions"
on public.book_submissions for delete
using (public.is_platform_admin());

-- 3. Removed Core Catalog Books
create table if not exists public.removed_catalog_books (
    book_id int primary key,
    removed_at timestamptz default now() not null,
    removed_by uuid references auth.users(id) on delete set null
);

alter table public.removed_catalog_books enable row level security;

drop policy if exists "Anyone can read removed catalog books" on public.removed_catalog_books;
create policy "Anyone can read removed catalog books"
on public.removed_catalog_books for select
using (true);

drop policy if exists "Owner can insert removed catalog books" on public.removed_catalog_books;
create policy "Owner can insert removed catalog books"
on public.removed_catalog_books for insert
with check (public.is_platform_admin());

drop policy if exists "Owner can delete removed catalog books" on public.removed_catalog_books;
create policy "Owner can delete removed catalog books"
on public.removed_catalog_books for delete
using (public.is_platform_admin());

-- 4. Supabase Storage Bucket Configuration
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'book-submissions',
    'book-submissions',
    true,
    52428800,
    array['application/pdf']
)
on conflict (id) do update set
    public = true,
    file_size_limit = 52428800,
    allowed_mime_types = array['application/pdf'];

-- Storage Access Policies
drop policy if exists "Public read book-submissions" on storage.objects;
drop policy if exists "Public insert book-submissions" on storage.objects;
drop policy if exists "Owner update book-submissions" on storage.objects;
drop policy if exists "Owner delete book-submissions" on storage.objects;

create policy "Public read book-submissions"
on storage.objects for select
using (bucket_id = 'book-submissions');

create policy "Public insert book-submissions"
on storage.objects for insert
with check (bucket_id = 'book-submissions');

create policy "Owner update book-submissions"
on storage.objects for update
using (
    bucket_id = 'book-submissions' and
    public.is_platform_admin()
);

create policy "Owner delete book-submissions"
on storage.objects for delete
using (
    bucket_id = 'book-submissions' and
    public.is_platform_admin()
);
